version: '3'

services:
  gekko:
    build: ./
    volumes:
      - ./volumes/gekko/history:/usr/src/app/history
    environment:
     - HOST
     - PORT
     - USE_SSL
    ports:
      - "${PORT}:${PORT}"